// <auto-generated />
namespace MeetMeWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Meeting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Meeting));
        
        string IMigrationMetadata.Id
        {
            get { return "201705221848276_Meeting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
